[versions]
annotation = "1.9.1"
agp = "9.0.1"

[plugins]
agp-lib = { id = "com.android.library", version.ref = "agp" }

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
